export const yardDetail = [
  {
    id: 1,
    Name: "Samir Truck Wreckers",
    Email: "samircarremoval@gmail.com",
    Phone: "0402 639 249",
    Address: "1/48, Pendlebury Road, Cardiff, 2285, Newcastle, New South Wales",
    Country: "Australia",
    City: "Cardiff",
    Services: {
      service1: "Wreckers",
      service2: "Auto Parts",
    },
    AdditionalInformation:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to take a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    WebsiteUrl: "https://www.samirtruckwreckers.com.au/",
    Logo: "/avatars/samirtruck.png",
    Image1: "./avatars/yard.jpeg",
    Image2: "./avatars/yard.jpeg",
    Image3: "./avatars/yard.jpeg",
    Image4: "./avatars/yard.jpeg",
    FacebookLink: "",
    LinkeinLink: "",
    PinterestLink: "",
    TwitterLink: "",
  },
  {
    id: 2,
    Name: "5B Car Removal Newcastle",
    Email: "samircarremoval@gmail.com",
    Phone: "0402 639 249",
    Address: "1/48, Pendlebury Road, Cardiff, 2285, Newcastle, New South Wales",
    Country: "Australia",
    City: "Cardiff",
    Services: {
      service1: "Wreckers",
      service2: "Auto Parts",
    },
    AdditionalInformation:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to take a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    WebsiteUrl: "https://www.samirtruckwreckers.com.au/",
    Logo: "/avatars/samirtruck.png",
    Image1: "./avatars/yard.jpeg",
    Image2: "./avatars/yard.jpeg",
    Image3: "./avatars/yard.jpeg",
    Image4: "./avatars/yard.jpeg",
    FacebookLink: "",
    LinkeinLink: "",
    PinterestLink: "",
    TwitterLink: "",
  },
  {
    id: 3,
    Name: "Viper Cash For Cars",
    Email: "samircarremoval@gmail.com",
    Phone: "0402 639 249",
    Address: "1/48, Pendlebury Road, Cardiff, 2285, Newcastle, New South Wales",
    Country: "Australia",
    City: "Cardiff",
    Services: {
      service1: "Wreckers",
      service2: "Auto Parts",
    },
    AdditionalInformation:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to take a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    WebsiteUrl: "https://www.samirtruckwreckers.com.au/",
    Logo: "/avatars/samirtruck.png",
    Image1: "./avatars/yard.jpeg",
    Image2: "./avatars/yard.jpeg",
    Image3: "./avatars/yard.jpeg",
    Image4: "./avatars/yard.jpeg",
    FacebookLink: "",
    LinkeinLink: "",
    PinterestLink: "",
    TwitterLink: "",
  },
  {
    id: 4,
    Name: "Grande Wreckers",
    Email: "samircarremoval@gmail.com",
    Phone: "0402 639 249",
    Address: "1/48, Pendlebury Road, Cardiff, 2285, Newcastle, New South Wales",
    Country: "Australia",
    City: "Cardiff",
    Services: {
      service1: "Wreckers",
      service2: "Auto Parts",
    },
    AdditionalInformation:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to take a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    WebsiteUrl: "https://www.samirtruckwreckers.com.au/",
    Logo: "/avatars/samirtruck.png",
    Image1: "./avatars/yard.jpeg",
    Image2: "./avatars/yard.jpeg",
    Image3: "./avatars/yard.jpeg",
    Image4: "./avatars/yard.jpeg",
    FacebookLink: "",
    LinkeinLink: "",
    PinterestLink: "",
    TwitterLink: "",
  },
  {
    id: 5,
    Name: "Samir Car Removals",
    Email: "samircarremoval@gmail.com",
    Phone: "0402 639 249",
    Address: "1/48, Pendlebury Road, Cardiff, 2285, Newcastle, New South Wales",
    Country: "Australia",
    City: "Cardiff",
    Services: {
      service1: "Wreckers",
      service2: "Auto Parts",
    },
    AdditionalInformation:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to take a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    WebsiteUrl: "https://www.samirtruckwreckers.com.au/",
    Logo: "/avatars/samirtruck.png",
    Image1: "./avatars/yard.jpeg",
    Image2: "./avatars/yard.jpeg",
    Image3: "./avatars/yard.jpeg",
    Image4: "./avatars/yard.jpeg",
    FacebookLink: "",
    LinkeinLink: "",
    PinterestLink: "",
    TwitterLink: "",
  },
];
